SELECT * FROM Coviddeaths

SELECT * FROM covidvacc

-- SELECT DATA THAT WE ARE GOING TO BE USING

SELECT LOCATION,DATE,total_cases,new_cases,total_deaths,population
FROM Coviddeaths
ORDER BY 1,2

-- LOOKING AT TOTAL CASES VS TOTAL DEATHS
-- SHOWS LIKELIHOOD OF DYING IF YOU CONTRACT COVID IN YOUR COUNTRY

SELECT LOCATION, DATE, total_cases,total_deaths,(TOTAL_DEATHS/TOTAL_CASES)*100 AS DEATHPERCENTAGE
FROM Coviddeaths
WHERE LOCATION LIKE '%STATES%'
ORDER BY 1,2

--LOOKING AT TOTAL CAES VS POPULATION
-- SHOWS WHAT PERCENTAGE OF POPULATION GOT COVID

SELECT LOCATION, DATE, total_cases,POPULATION,(total_cases/POPULATION)*100 AS DEATHPERCENTAGE
FROM Coviddeaths
WHERE LOCATION LIKE '%STATES%'
ORDER BY 1,2

--LOOKING AT COUNTRIES WITH HIGHEST INFECTION RATE COMPARED TO POPULATION

SELECT LOCATION ,POPULATION,MAX(TOTAL_CASES) AS HIGHESTINFECTIONCOUNT , 
MAX(TOTAL_CASES/POPULATION)*100 AS DEATHPERCENTAGE 
FROM PortfolioProject..Coviddeaths
GROUP BY LOCATION,population
ORDER BY DEATHPERCENTAGE DESC

--SHOWING THE COUNTRY HIGHEST DEATH COUNT PER POPULATION
SELECT LOCATION ,MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT  
FROM PortfolioProject..Coviddeaths
WHERE continent IS NOT NULL
GROUP BY LOCATION
ORDER BY TOTALDEATHCOUNT DESC

-- LET'S BREAK THINGS DOWN BY CONTINENT

SELECT location,MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT  
FROM PortfolioProject..Coviddeaths
WHERE continent IS NULL
GROUP BY location
ORDER BY TOTALDEATHCOUNT DESC

-- GLOBAL NUMBERS
SELECT SUM(new_cases) AS TOTAL_CASES,SUM(CAST(NEW_deaths AS INT)), SUM(CAST(new_deaths AS INT))/SUM(
NEW_cases)*100
AS DEATHPERCENTAGE 
FROM PortfolioProject..Coviddeaths
WHERE continent IS NOT NULL
--GROUP BY DATE
ORDER BY 1,2

-- LOOKING AT TOTAL POPULATION VS VACCINATIONS
SELECT DEA.continent,DEA.location,DEA.date,DEA.population,VAC.new_vaccinations 
, SUM(CONVERT(INT,VAC.NEW_VACCINATIONS ))OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,
DEA.DATE) AS ROLLINGPEOPLEVACCINNATED
FROM Coviddeaths DEA
JOIN covidvacc VAC
   ON DEA.LOCATION = VAC.location
   AND DEA.DATE  = VAC.DATE
WHERE DEA.continent IS NOT NULL
ORDER BY 2,3

-- USE CTE

WITH POPVSVAC(CONTINENT,LOCATION,DATE, POPULATION,new_vaccinations,ROLLINGPEOPLEVACCINNATED)
AS
(
SELECT DEA.continent,DEA.location,DEA.date,DEA.population,VAC.new_vaccinations 
, SUM(CONVERT(INT,VAC.NEW_VACCINATIONS ))OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,
DEA.DATE) AS ROLLINGPEOPLEVACCINNATED
FROM Coviddeaths DEA
JOIN covidvacc VAC
   ON DEA.LOCATION = VAC.location
   AND DEA.DATE  = VAC.DATE
WHERE DEA.continent IS NOT NULL
--ORDER BY 2,3
)

SELECT *,(ROLLINGPEOPLEVACCINNATED/POPULATION)*100
FROM POPVSVAC


-- TEMP TABLES
DROP TABLE IF EXISTS #PERCENTPOPULATIONVACCIIANTED
CREATE TABLE #PERCENTPOPULATIONVACCIIANTED
(
CONTINENT NVARCHAR(255),
LOCATION NVARCHAR(255),
DATTE DATETIME,
POPULATION NUMERIC,
NEW_VACCINATIONS NUMERIC,
ROLLINGPEOPLEVACCINNATED NUMERIC)

INSERT INTO  #PERCENTPOPULATIONVACCIIANTED
SELECT DEA.continent,DEA.location,DEA.date,DEA.population,VAC.new_vaccinations 
, SUM(CONVERT(INT,VAC.NEW_VACCINATIONS ))OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,
DEA.DATE) AS ROLLINGPEOPLEVACCINNATED
FROM Coviddeaths DEA
JOIN covidvacc VAC
   ON DEA.LOCATION = VAC.location
   AND DEA.DATE  = VAC.DATE
--WHERE DEA.continent IS NOT NULL
--ORDER BY 2,3

SELECT *,(ROLLINGPEOPLEVACCINNATED/POPULATION)*100
FROM #PERCENTPOPULATIONVACCIIANTED



-- CREATING VIEW TO  STORE DATAA FOR LATER VISUALIZATION

CREATE VIEW  PERCENTPOPULATIONVACCINATED AS
SELECT DEA.continent,DEA.location,DEA.date,DEA.population,VAC.new_vaccinations 
, SUM(CONVERT(INT,VAC.NEW_VACCINATIONS ))OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,
DEA.DATE) AS ROLLINGPEOPLEVACCINNATED
FROM Coviddeaths DEA
JOIN covidvacc VAC
   ON DEA.LOCATION = VAC.location
   AND DEA.DATE  = VAC.DATE
--WHERE DEA.continent IS NOT NULL
--ORDER BY 2,3

SELECT * FROM PERCENTPOPULATIONVACCINATED
